### ISSUE TITLE
Concerns about the Monet code

### ISSUE THREAD

**Issue by khalwat** [dyerc/craft-monet#1]
Chris, I have some concerns about some of the code in your Monet plugin.

I'm totally fine (and even encourage) people to take things from my articles and put them into practice, or to use my plugin source code as a learning tool.

But I feel like a line has been crossed here in terms of code being repurposed. I haven't done a full audit of the code, but from a short scan:

https://github.com/dyerc/craft-monet/blob/d03ab9236cf2159c86e291138ec0e06abc855cc1/src/services/MonetService.php#L20 -> https://github.com/nystudio107/craft-imageoptimize/blob/87b49058766aecffc079a149c4c0167a5ffc8e4a/src/services/Placeholder.php#L37

<https://github.com/dyerc/craft-monet/blob/d03ab9236cf2159c86e291138ec0e06abc855cc1/src/services/MonetService.php#L93> -> <https://github.com/nystudio107/craft-imageoptimize/blob/87b49058766aecffc079a149c4c0167a5ffc8e4a/src/services/Placeholder.php#L109>

<https://github.com/dyerc/craft-monet/blob/d03ab9236cf2159c86e291138ec0e06abc855cc1/src/services/MonetService.php#L170> -> <https://github.com/nystudio107/craft-imageoptimize/blob/87b49058766aecffc079a149c4c0167a5ffc8e4a/src/services/Placeholder.php#L270>

...it seems pretty clear to me that some of this code has been copied & pasted from ImageOptimize.

Look at this method from Monet:

```php
    public function generateColorPalette(string $tempPath): array
    {
        Craft::beginProfile('generateColorPalette', __METHOD__);
        Craft::info('Generate colour palette from image', __METHOD__);

        $colours = [];

        if (!empty($tempPath)) {
            try {
                $palette = ColorThief::getPalette($tempPath, 5);
            } catch (\Exception $e) {
                Craft::error($e->getMessage(), __METHOD__);
                return [];
            }

            foreach ($palette as $colour) {
                $colours[] = sprintf('#%02x%02x%02x', $colour[0], $colour[1], $colour[2]);
            }
        }

        Craft::endProfile('generateColorPalette', __METHOD__);

        return $colours;
    }
```

...and compare it to this method from ImageOptimize: 

```php
    public function generateColorPalette(string $tempPath): array
    {
        Craft::beginProfile('generateColorPalette', __METHOD__);
        Craft::info(
            'Generating color palette for: ' . $tempPath,
            __METHOD__
        );
        $colorPalette = [];
        if (!empty($tempPath)) {
            // Extract the color palette
            try {
                $palette = ColorThief::getPalette($tempPath, 5);
            } catch (\Exception $e) {
                Craft::error($e->getMessage(), __METHOD__);

                return [];
            }
            // Convert RGB to hex color
            foreach ($palette as $colors) {
                $colorPalette[] = sprintf('#%02x%02x%02x', $colors[0], $colors[1], $colors[2]);
            }
        }
        Craft::endProfile('generateColorPalette', __METHOD__);

        return $colorPalette;
    }
```

For reference, another plugin, Imager X, also extracts a color palette using `ColorThief`, but the implementation is quite different: https://github.com/spacecatninja/craft-imager-x/blob/2167371e921d2a9c89db763265d8eb7029a225d8/src/services/ImagerColorService.php#L79

While I encourage your contributions to the Craft ecosystem, I would appreciate it if source code was used as a learning reference from which you write your own solutions to a given problem.

My concern isn't just this particular instance, but rather the larger ecosystem for Craft CMS plugin development, and the norms that we condone.

I'm not expecting you to go in and rewrite working code (unless you want to!), but I'd at least appreciate an accreditation in the docs & source code comment. And obviously, going forward, I'm hoping to not run into this situation in the future.

**Comment by khalwat** [comment]
Looks like it's a bit more than just this one file that I looked at earlier:

<img width="1509" alt="monet-code-dups" src="https://user-images.githubusercontent.com/7570798/210693848-2270bb90-66e9-43f6-9818-20709414b4d6.png">

The number next to **Cost** is the number of duplicate lines of code the files

**Comment by dyerc** [comment]
Hi Andrew,

I’m very sorry that you feel I have plagiarised from one of your Craft plugins. I realise that Monet has a small overlap with a couple of ImageOptimize’s features, although I hope that Monet’s features make it a unique and useful plugin in its own right.

Have I looked at Craft’s core code and other plugins in order to figure out how to solve certain problems and work within Craft’s API, yes of course. However, if you think I have copied great chunks of one of your plugins and simply pasted them as my own work, I would have to disagree.

Where variable names and constants overlap between our plugins, as they are bound to do between any Craft plugins, especially those that deal with the same Craft image resizing methods etc, I don’t find that particularly surprising. When I search GitHub for some of the lines you have highlighted I can find countless other repositories containing exactly the same. Especially the following lines for instance which are directly from Craft itself:

```
// This might take a while
App::maxPowerCaptain();
$queue = Craft::$app->getQueue();
```

I have bought many of your plugins in the past (including ImageOptimize) and you are one of the most well respected names in the Craft world, the last thing I want do is start upsetting anyone. However, I must admit that I was upset yesterday evening by your terse and strongly worded messages. The last thing I want is any hostility, so I think the best option is that I will refactor these specific lines of code you have an issue with, to remove any possible doubt, which I will do now.

**Comment by khalwat** [comment]
> However, if you think I have copied great chunks of one of your plugins and simply pasted them as my own work, I would have to disagree.

If you want to go down this road, we can.

Can you explain to me how that `generateColorPalette()` method is line for line the same, including:

* Profiling statements that you don't use elsewhere in your code, outside of this file
* The method name spelling "color" using the American spelling, rather than British
* The use of `sprintf()` to convert colors from hex to RGB

A few variables are renamed, but this is the same chunk of code. And there are other places throughout the code base that make it clear other code was wholesale copied, modified, and used.

> However, I must admit that I was upset yesterday evening by your terse and strongly worded messages. The last thing I want is any hostility, so I think the best option is that I will refactor these specific lines of code you have an issue with, to remove any possible doubt, which I will do now.

As was I when I saw my unattributed code in the Monet plugin.

I've shown the code comparison to several experienced developers, and they have all come to the same conclusion that I have.

I wouldn't have said anything if I wasn't quite certain.

**Comment by dyerc** [comment]
I felt I had given a comprehensive reply previously and something that I felt was a benefit to the community has proven more hassle than it’s worth. So rather than me composing a long reply outlining the history of that code including the StackOverflow link for using `sprintf`, I think I’m just going to delete this repository and move on with my life.
